// Database di domande sul Tennis (100+ Domande - Risultati & Tecnica Base)
const tennisQuestions = [
    // ==================== TECNICA & REGOLE (BASE) ====================
    { category: "Tecnica", question: "Come si chiama il colpo eseguito al volo vicino alla rete?", answers: ["Volée", "Smash", "Lob", "Dritto"], correct: 0 },
    { category: "Tecnica", question: "Quale colpo si usa per scavalcare un avversario a rete?", answers: ["Lob (Pallonetto)", "Smorzata", "Passante", "Slice"], correct: 0 },
    { category: "Tecnica", question: "Come si chiama il servizio che tocca la rete e cade nel campo giusto?", answers: ["Let", "Fault", "Ace", "Out"], correct: 0 },
    { category: "Tecnica", question: "Quale punteggio indica la parità 40-40?", answers: ["Deuce", "Love", "Advantage", "Break"], correct: 0 },
    { category: "Tecnica", question: "Qual è il punteggio 'zero' nel tennis?", answers: ["Love", "Null", "Zero", "Ouch"], correct: 0 },
    { category: "Tecnica", question: "Come si chiama il colpo che colpisce la palla sopra la testa con forza?", answers: ["Smash", "Volée", "Lob", "Slice"], correct: 0 },
    { category: "Tecnica", question: "Quale superficie è la più veloce?", answers: ["Erba", "Terra Rossa", "Cemento Lento", "Sabbia"], correct: 0 },
    { category: "Tecnica", question: "Su quale superficie la palla rimbalza più alta e lenta?", answers: ["Terra Rossa", "Erba", "Cemento", "Parquet"], correct: 0 },
    { category: "Tecnica", question: "Quanti set deve vincere un uomo negli Slam per portare a casa il match?", answers: ["3", "2", "4", "5"], correct: 0 },
    { category: "Tecnica", question: "Cos'è un 'Ace'?", answers: ["Servizio vincente non toccato dall'avversario", "Servizio che tocca la rete", "Colpo vincente di dritto", "Doppio fallo"], correct: 0 },
    { category: "Tecnica", question: "Cosa significa 'Break'?", answers: ["Vincere un game sul servizio avversario", "Rompere la racchetta", "Una pausa tra i game", "Vincere il set"], correct: 0 },
    { category: "Tecnica", question: "Quanti punti vale il primo punto di un game?", answers: ["15", "10", "1", "30"], correct: 0 },
    { category: "Tecnica", question: "Come si chiama l'effetto che fa ruotare la palla all'indietro (basso rimbalzo)?", answers: ["Slice / Backspin", "Topspin", "Flat", "Kick"], correct: 0 },
    { category: "Tecnica", question: "Quanti scambi sono permessi prima che la palla rimbalzi due volte?", answers: ["Infiniti (finché non cade)", "Massimo 10", "Massimo 20", "Massimo 5"], correct: 0 },
    { category: "Tecnica", question: "Quale riga delimita il campo di singolare lateralmente?", answers: ["La riga interna (corridoi esclusi)", "La riga esterna", "La riga di servizio", "La riga di fondo"], correct: 0 },
    { category: "Tecnica", question: "Chi chiama 'Out' le palle nel tennis professionale?", answers: ["I giudici di linea (o occhio di falco)", "L'arbitro di sedia soltanto", "Il pubblico", "I giocatori"], correct: 0 },
    { category: "Tecnica", question: "Come si chiama il colpo giocato subito dopo il rimbalzo, quasi di controbalzo?", answers: ["Demi-volée", "Smash", "Lob", "Veronica"], correct: 0 },
    { category: "Tecnica", question: "Cos'è il 'Tie-break'?", answers: ["Un game decisivo sul 6-6", "Una pausa per pioggia", "Il riscaldamento", "L'ultimo punto del match"], correct: 0 },
    { category: "Tecnica", question: "Ogni quanti game si cambiano le palle (solitamente)?", answers: ["Ogni 9 (o 7 all'inizio)", "Ogni 5", "Ogni set", "Mai"], correct: 0 },
    { category: "Tecnica", question: "Cosa succede se un giocatore tocca la rete mentre la palla è in gioco?", answers: ["Perde il punto", "Si ripete il punto", "Vince il punto", "Nulla"], correct: 0 },

    // ==================== RISULTATI & STORIA (80+ DOMANDE) ====================
    { category: "Risultati", question: "Chi ha vinto l'Australian Open 2024 Maschile?", answers: ["Jannik Sinner", "Novak Djokovic", "Daniil Medvedev", "Carlos Alcaraz"], correct: 0 },
    { category: "Risultati", question: "Chi ha vinto il Roland Garros 2024 Maschile?", answers: ["Carlos Alcaraz", "Alexander Zverev", "Jannik Sinner", "Novak Djokovic"], correct: 0 },
    { category: "Risultati", question: "Chi detiene il record di titoli Slam maschili (24)?", answers: ["Novak Djokovic", "Rafael Nadal", "Roger Federer", "Pete Sampras"], correct: 0 },
    { category: "Risultati", question: "Quante volte Nadal ha vinto il Roland Garros?", answers: ["14", "13", "12", "15"], correct: 0 },
    { category: "Risultati", question: "Chi ha vinto 8 titoli a Wimbledon (record maschile)?", answers: ["Roger Federer", "Novak Djokovic", "Pete Sampras", "Björn Borg"], correct: 0 },
    { category: "Risultati", question: "Quale Italiano ha vinto la Coppa Davis nel 1976?", answers: ["Panatta, Barazzutti, Bertolucci, Zugarelli", "Sinner, Musetti, Berrettini", "Fognini, Bolelli, Seppi", "Pietrangeli, Sirola"], correct: 0 },
    { category: "Risultati", question: "In che anno l'Italia ha vinto la sua seconda Coppa Davis?", answers: ["2023", "2022", "2021", "2024"], correct: 0 },
    { category: "Risultati", question: "Chi è stato il primo italiano n.1 al mondo ATP?", answers: ["Jannik Sinner", "Adriano Panatta", "Nicola Pietrangeli", "Matteo Berrettini"], correct: 0 },
    { category: "Risultati", question: "Chi ha vinto l'Oro Olimpico singolare maschile a Parigi 2024?", answers: ["Novak Djokovic", "Carlos Alcaraz", "Lorenzo Musetti", "Alexander Zverev"], correct: 0 },
    { category: "Risultati", question: "Quale donna ha vinto 23 Slam nell'Era Open?", answers: ["Serena Williams", "Steffi Graf", "Martina Navratilova", "Chris Evert"], correct: 0 },
    { category: "Risultati", question: "Chi ha completato il Grande Slam nel 1969?", answers: ["Rod Laver", "Ken Rosewall", "Arthur Ashe", "Roy Emerson"], correct: 0 },
    { category: "Risultati", question: "Chi ha vinto Wimbledon 2013 riportando il titolo in Gran Bretagna dopo 77 anni?", answers: ["Andy Murray", "Tim Henman", "Greg Rusedski", "Cameron Norrie"], correct: 0 },
    { category: "Risultati", question: "Quale giocatore è noto come 'The King of Clay'?", answers: ["Rafael Nadal", "Roger Federer", "Guillermo Vilas", "Gustavo Kuerten"], correct: 0 },
    { category: "Risultati", question: "Chi ha vinto lo US Open 2021 impedendo il Grande Slam a Djokovic?", answers: ["Daniil Medvedev", "Alexander Zverev", "Stefanos Tsitsipas", "Matteo Berrettini"], correct: 0 },
    { category: "Risultati", question: "Quale italiano ha raggiunto la finale di Wimbledon 2021?", answers: ["Matteo Berrettini", "Jannik Sinner", "Fabio Fognini", "Lorenzo Musetti"], correct: 0 },
    { category: "Risultati", question: "Chi è il più giovane numero 1 della storia ATP?", answers: ["Carlos Alcaraz", "Lleyton Hewitt", "Jannik Sinner", "Marat Safin"], correct: 0 },
    { category: "Risultati", question: "Quale torneo completa il Grande Slam cronologicamente?", answers: ["US Open", "Australian Open", "Wimbledon", "Roland Garros"], correct: 0 },
    { category: "Risultati", question: "Chi ha vinto 5 Wimbledon consecutivi dal 1976 al 1980?", answers: ["Björn Borg", "John McEnroe", "Jimmy Connors", "Ivan Lendl"], correct: 0 },
    { category: "Risultati", question: "Quale tennista svizzero ha vinto 20 Slam?", answers: ["Roger Federer", "Stan Wawrinka", "Marc Rosset", "Heinz Gunthardt"], correct: 0 },
    { category: "Risultati", question: "Chi ha vinto la Coppa Davis 2022?", answers: ["Canada", "Australia", "Italia", "Spagna"], correct: 0 },
    { category: "Risultati", question: "Chi ha vinto il torneo di Roma (Internazionali d'Italia) nel 2024?", answers: ["Alexander Zverev", "Nicolas Jarry", "Novak Djokovic", "Jannik Sinner"], correct: 0 },
    { category: "Risultati", question: "Qual è il torneo più antico del mondo?", answers: ["Wimbledon", "US Open", "Roland Garros", "Davis Cup"], correct: 0 },
    { category: "Risultati", question: "Chi ha vinto 10 volte l'Australian Open (record)?", answers: ["Novak Djokovic", "Roger Federer", "Andre Agassi", "Roy Emerson"], correct: 0 },
    { category: "Risultati", question: "Quanti Slam ha vinto Andy Murray?", answers: ["3", "2", "4", "1"], correct: 0 },
    { category: "Risultati", question: "Chi ha vinto il singolare femminile allo US Open 2015 (finale tutta italiana)?", answers: ["Flavia Pennetta", "Roberta Vinci", "Francesca Schiavone", "Sara Errani"], correct: 0 },
    { category: "Risultati", question: "Quale italiana ha vinto il Roland Garros 2010?", answers: ["Francesca Schiavone", "Flavia Pennetta", "Sara Errani", "Roberta Vinci"], correct: 0 },
    { category: "Risultati", question: "Chi è l'unico giocatore ad aver vinto due volte l'Oro Olimpico in singolare (maschile)?", answers: ["Andy Murray", "Rafael Nadal", "Roger Federer", "Novak Djokovic"], correct: 0 },
    { category: "Risultati", question: "Chi ha vinto le ATP Finals 2023 a Torino?", answers: ["Novak Djokovic", "Jannik Sinner", "Daniil Medvedev", "Carlos Alcaraz"], correct: 0 },
    { category: "Risultati", question: "Quale nazione ospita il Roland Garros?", answers: ["Francia", "Spagna", "Italia", "Svizzera"], correct: 0 },
    { category: "Risultati", question: "Chi ha vinto il Masters 1000 di Monte-Carlo per 11 volte?", answers: ["Rafael Nadal", "Novak Djokovic", "Björn Borg", "Thomas Muster"], correct: 0 },
    { category: "Risultati", question: "Quale giocatore è famoso per il suo servizio 'impossibile' (record velocità)?", answers: ["John Isner / Sam Groth", "Roger Federer", "Rafael Nadal", "David Ferrer"], correct: 0 }, // Simplified answer for recognition
    { category: "Risultati", question: "Chi ha vinto l'ultima edizione della Hopman Cup (2023)?", answers: ["Croazia", "Svizzera", "Francia", "USA"], correct: 0 },
    { category: "Risultati", question: "In quale città si svolgono le ATP Finals dal 2021?", answers: ["Torino", "Londra", "Shanghai", "New York"], correct: 0 },
    { category: "Risultati", question: "Qual è lo Slam che si gioca sull'erba?", answers: ["Wimbledon", "Roland Garros", "US Open", "Australian Open"], correct: 0 },
    { category: "Risultati", question: "Chi ha vinto il primo Slam dell'Era Open (Roland Garros 1968)?", answers: ["Ken Rosewall", "Rod Laver", "Andrés Gimeno", "Pancho Gonzales"], correct: 0 },
    { category: "Risultati", question: "Quale giocatore ha vinto Wimbledon a 17 anni nel 1985?", answers: ["Boris Becker", "Stefan Edberg", "Mats Wilander", "Ivan Lendl"], correct: 0 },
    { category: "Risultati", question: "Chi ha vinto lo US Open 2022?", answers: ["Carlos Alcaraz", "Casper Ruud", "Frances Tiafoe", "Karen Khachanov"], correct: 0 },
    { category: "Risultati", question: "Quale coppia italiana ha vinto l'Australian Open 2015 di doppio maschile?", answers: ["Fognini / Bolelli", "Sinner / Sonego", "Panatta / Bertolucci", "Seppi / Starace"], correct: 0 },
    { category: "Risultati", question: "Chi ha vinto il singolare femminile a Wimbledon 2024?", answers: ["Barbora Krejcikova", "Jasmine Paolini", "Iga Swiatek", "Elena Rybakina"], correct: 0 },
    { category: "Risultati", question: "Chi è stata la prima finalista italiana a Wimbledon (2024)?", answers: ["Jasmine Paolini", "Flavia Pennetta", "Sara Errani", "Camila Giorgi"], correct: 0 },
    { category: "Risultati", question: "Chi ha vinto la medaglia di Bronzo a Parigi 2024 (Singolare Maschile)?", answers: ["Lorenzo Musetti", "Felix Auger-Aliassime", "Tommy Paul", "Casper Ruud"], correct: 0 },
    { category: "Risultati", question: "Chi ha vinto l'Oro nel doppio femminile a Parigi 2024?", answers: ["Errani / Paolini", "Gauff / Pegula", "Krejcikova / Siniakova", "Bucsa / Sorribes Tormo"], correct: 0 },
    { category: "Risultati", question: "Quanti Master 1000 ha vinto Fabio Fognini?", answers: ["1 (Montecarlo)", "2", "0", "3"], correct: 0 },
    { category: "Risultati", question: "Chi ha battuto Federer nella sua ultima partita ufficiale (Wimbledon 2021)?", answers: ["Hubert Hurkacz", "Lorenzo Sonego", "Felix Auger-Aliassime", "Matteo Berrettini"], correct: 0 },
    { category: "Risultati", question: "Con chi ha giocato Federer la sua ultima partita in Laver Cup?", answers: ["Rafael Nadal", "Novak Djokovic", "Andy Murray", "Stan Wawrinka"], correct: 0 },
    { category: "Risultati", question: "Chi ha vinto il titolo a Indian Wells 2024?", answers: ["Carlos Alcaraz", "Daniil Medvedev", "Jannik Sinner", "Tommy Paul"], correct: 0 },
    { category: "Risultati", question: "Chi ha vinto il titolo a Miami 2024?", answers: ["Jannik Sinner", "Grigor Dimitrov", "Daniil Medvedev", "Alexander Zverev"], correct: 0 },
    { category: "Risultati", question: "Quale superficie è utilizzata allo US Open?", answers: ["Cemento (DecoTurf/Laykold)", "Terra Verde", "Erba", "Moquette"], correct: 0 },
    { category: "Risultati", question: "In che anno Roger Federer ha vinto il suo unico Roland Garros?", answers: ["2009", "2008", "2011", "2006"], correct: 0 },
    { category: "Risultati", question: "Chi ha battuto Nadal al Roland Garros 2009?", answers: ["Robin Söderling", "Novak Djokovic", "Roger Federer", "Andy Murray"], correct: 0 },
    { category: "Risultati", question: "Chi era il rivale principale di Björn Borg?", answers: ["John McEnroe", "Pete Sampras", "Andre Agassi", "Boris Becker"], correct: 0 },
    { category: "Risultati", question: "Chi era il rivale principale di Andre Agassi?", answers: ["Pete Sampras", "Jim Courier", "Michael Chang", "Boris Becker"], correct: 0 },
    { category: "Risultati", question: "Chi ha vinto più titoli a Parigi-Bercy?", answers: ["Novak Djokovic", "Marat Safin", "Boris Becker", "Pete Sampras"], correct: 0 },
    { category: "Risultati", question: "Quale giocatore è soprannominato 'Nole'?", answers: ["Novak Djokovic", "Goran Ivanisevic", "Marin Cilic", "Ivan Ljubicic"], correct: 0 },
    { category: "Risultati", question: "Quale giocatore è soprannominato 'Rafa'?", answers: ["Rafael Nadal", "Rafael Osuna", "Patrick Rafter", "Raphael Collignon"], correct: 0 },
    { category: "Risultati", question: "In che anno Sinner ha vinto le Next Gen ATP Finals?", answers: ["2019", "2020", "2018", "2021"], correct: 0 },
    { category: "Risultati", question: "Chi ha vinto il torneo di Wimbledon 2022?", answers: ["Novak Djokovic", "Nick Kyrgios", "Cameron Norrie", "Rafael Nadal"], correct: 0 },
    { category: "Risultati", question: "Chi ha vinto lo US Open 2020 (Thiem vs Zverev)?", answers: ["Dominic Thiem", "Alexander Zverev", "Daniil Medvedev", "Pablo Carreno Busta"], correct: 0 },
    { category: "Risultati", question: "Quale sorella Williams ha vinto più Slam?", answers: ["Serena", "Venus", "Hanno gli stessi titoli", "Nessuna delle due"], correct: 0 },
    { category: "Risultati", question: "Chi ha vinto il singolare femminile all'Australian Open 2023?", answers: ["Aryna Sabalenka", "Elena Rybakina", "Iga Swiatek", "Ons Jabeur"], correct: 0 },
    { category: "Risultati", question: "Quante settimane (totali) Steffi Graf è stata numero 1?", answers: ["377", "310", "332", "260"], correct: 0 },
    { category: "Risultati", question: "Quale giocatore ha vinto il Career Golden Masters (tutti i Masters 1000)?", answers: ["Novak Djokovic", "Roger Federer", "Rafael Nadal", "Andy Murray"], correct: 0 },
    { category: "Risultati", question: "Chi ha vinto la United Cup 2024?", answers: ["Germania", "Polonia", "Australia", "Francia"], correct: 0 },
    { category: "Risultati", question: "Chi ha vinto la Laver Cup 2024?", answers: ["Team Europe", "Team World", "Nessuno", "Pareggio"], correct: 0 },
    { category: "Risultati", question: "Quale tennista ha vinto 4 volte il torneo di Roma negli anni '30?", answers: ["Nessuno (Pietrangeli ne ha vinti 2)", "Nicola Pietrangeli", "Giovanni Palmieri", "Giorgio De Stefani"], correct: 1 }, // Trick naming check
    { category: "Risultati", question: "Quanti titoli ha vinto Nicola Pietrangeli al Roland Garros?", answers: ["2", "1", "3", "0"], correct: 0 },
    { category: "Risultati", question: "In che anno l'Italia femminile ha vinto la sua prima Fed Cup?", answers: ["2006", "2009", "2010", "2013"], correct: 0 },
    { category: "Risultati", question: "Chi era il capitano dell'Italia in Coppa Davis 2023?", answers: ["Filippo Volandri", "Corrado Barazzutti", "Adriano Panatta", "Paolo Bertolucci"], correct: 0 },
    { category: "Risultati", question: "Quale torneo non fa parte dei Masters 1000?", answers: ["Barcellona (ATP 500)", "Indian Wells", "Miami", "Madrid"], correct: 0 },
    { category: "Risultati", question: "Chi ha vinto il torneo di Cincinnati 2024?", answers: ["Jannik Sinner", "Frances Tiafoe", "Alexander Zverev", "Holger Rune"], correct: 0 },
    { category: "Risultati", question: "Chi ha vinto lo US Open 2024 Maschile?", answers: ["Jannik Sinner", "Taylor Fritz", "Jack Draper", "Frances Tiafoe"], correct: 0 },
    { category: "Risultati", question: "Quanti Slam ha vinto Jannik Sinner nel 2024?", answers: ["2 (Aus Open, US Open)", "1", "3", "0"], correct: 0 },
    { category: "Risultati", question: "Chi ha vinto il singolare femminile al Roland Garros 2023?", answers: ["Iga Swiatek", "Karolina Muchova", "Aryna Sabalenka", "Coco Gauff"], correct: 0 },
    { category: "Risultati", question: "Chi ha vinto Wimbledon 2023 battendo Djokovic?", answers: ["Carlos Alcaraz", "Jannik Sinner", "Daniil Medvedev", "Holger Rune"], correct: 0 },
    { category: "Risultati", question: "Quale giocatore francese ha vinto il Roland Garros nell'Era Open?", answers: ["Yannick Noah", "Jo-Wilfried Tsonga", "Gael Monfils", "Henri Leconte"], correct: 0 },
    { category: "Risultati", question: "Chi ha vinto l'ATP di Halle per 10 volte?", answers: ["Roger Federer", "Lleyton Hewitt", "Tommy Haas", "Philipp Kohlschreiber"], correct: 0 },
    { category: "Risultati", question: "Quale giocatore è stato squalificato dallo US Open 2020?", answers: ["Novak Djokovic", "Nick Kyrgios", "Daniil Medvedev", "Benoit Paire"], correct: 0 },
    { category: "Risultati", question: "Chi ha vinto l'oro nel doppio maschile a Pechino 2008?", answers: ["Federer / Wawrinka", "Bryan / Bryan", "Nadal / Lopez", "Aspelin / Johansson"], correct: 0 },
    { category: "Risultati", question: "Quale paese ha vinto più Coppe Davis nella storia?", answers: ["USA", "Australia", "Francia", "Gran Bretagna"], correct: 0 },
    { category: "Risultati", question: "Chi ha vinto il Master 1000 di Parigi-Bercy 2022 (sorpresa)?", answers: ["Holger Rune", "Novak Djokovic", "Felix Auger-Aliassime", "Stefanos Tsitsipas"], correct: 0 },
    { category: "Risultati", question: "Quale tennista ha vinto il Roland Garros 2016 (maschile)?", answers: ["Novak Djokovic", "Andy Murray", "Stan Wawrinka", "Rafael Nadal"], correct: 0 },
    { category: "Risultati", question: "Chi ha vinto lo US Open 2014?", answers: ["Marin Cilic", "Kei Nishikori", "Roger Federer", "Novak Djokovic"], correct: 0 },
    { category: "Risultati", question: "Quale giocatore ha il record di Ace in una sola partita (113)?", answers: ["John Isner", "Nicolas Mahut", "Ivo Karlovic", "Reilly Opelka"], correct: 0 },
    { category: "Risultati", question: "Chi ha vinto il torneo di Vienna 2023?", answers: ["Jannik Sinner", "Daniil Medvedev", "Andrey Rublev", "Ben Shelton"], correct: 0 },
    { category: "Risultati", question: "Chi ha vinto il torneo di Pechino 2023?", answers: ["Jannik Sinner", "Daniil Medvedev", "Carlos Alcaraz", "Alexander Zverev"], correct: 0 },
    { category: "Risultati", question: "Chi è l'allenatore storico di Rafael Nadal (zio)?", answers: ["Toni Nadal", "Carlos Moya", "Francisco Roig", "Marc Lopez"], correct: 0 },
    { category: "Risultati", question: "Chi è l'allenatore storico di Novak Djokovic (fino al 2024)?", answers: ["Goran Ivanisevic", "Marian Vajda", "Boris Becker", "Andre Agassi"], correct: 0 },
    { category: "Risultati", question: "Quale giocatore ha vinto il titolo a Toronto 2023?", answers: ["Jannik Sinner", "Alex de Minaur", "Alejandro Davidovich Fokina", "Tommy Paul"], correct: 0 },
    { category: "Risultati", question: "In che anno Roger Federer si è ritirato?", answers: ["2022", "2021", "2023", "2020"], correct: 0 },
    { category: "Risultati", question: "Chi ha giocato l'ultima partita contro Serena Williams?", answers: ["Ajla Tomljanovic", "Ons Jabeur", "Anett Kontaveit", "Danka Kovinic"], correct: 0 },
    { category: "Risultati", question: "Chi ha vinto il singolare femminile a Wimbledon 2022?", answers: ["Elena Rybakina", "Ons Jabeur", "Simona Halep", "Ashleigh Barty"], correct: 0 },
    { category: "Risultati", question: "Quale nazione ha vinto la Billie Jean King Cup 2023?", answers: ["Canada", "Italia", "Australia", "Repubblica Ceca"], correct: 0 },
    { category: "Risultati", question: "Chi ha vinto il Masters 1000 di Shanghai 2023?", answers: ["Hubert Hurkacz", "Andrey Rublev", "Sebastian Korda", "Grigor Dimitrov"], correct: 0 },
    { category: "Risultati", question: "Qual è il colore della terra battuta a Madrid nel 2012 (esperimento)?", answers: ["Blu", "Verde", "Rossa", "Grigia"], correct: 0 },
    { category: "Risultati", question: "Chi ha vinto il torneo olimpico femminile a Rio 2016?", answers: ["Monica Puig", "Angelique Kerber", "Petra Kvitova", "Madison Keys"], correct: 0 },
    { category: "Risultati", question: "Chi ha vinto il torneo olimpico femminile a Tokyo 2020 (nel 2021)?", answers: ["Belinda Bencic", "Marketa Vondrousova", "Elina Svitolina", "Elena Rybakina"], correct: 0 },
    { category: "Risultati", question: "Chi ha vinto il torneo olimpico maschile a Tokyo 2020 (nel 2021)?", answers: ["Alexander Zverev", "Karen Khachanov", "Pablo Carreno Busta", "Novak Djokovic"], correct: 0 },
    { category: "Risultati", question: "Chi ha vinto le WTA Finals 2023?", answers: ["Iga Swiatek", "Jessica Pegula", "Aryna Sabalenka", "Coco Gauff"], correct: 0 },
    { category: "Risultati", question: "Quale giocatore italiano è entrato in Top 10 nel 2019?", answers: ["Matteo Berrettini", "Fabio Fognini", "Jannik Sinner", "Lorenzo Musetti"], correct: 0 },
    { category: "Risultati", question: "Chi ha vinto il torneo di Barcellona per 12 volte?", answers: ["Rafael Nadal", "Manuel Orantes", "Mats Wilander", "Carlos Alcaraz"], correct: 0 }
];

// Export for Node.js (server-side)
if (typeof module !== 'undefined' && module.exports) {
    module.exports = tennisQuestions;
}
